defaults:
  - evaluate
  - _self_

stage: offline_rl
init_from: ???

build_dataset:
  stage: ${stage}
  num_designs: ${num_designs}
  val_design_ratio: 0.2
  seed: 42
  scale_reward: true
  response_ratio: 0.5
  num_candidates: 20
  num_permutations: 2
  num_shots: 10

sft_config:
  # TrainingArguments
  output_dir: ${output_dir}
  per_device_train_batch_size: 4
  num_train_epochs: 50
  # https://openreview.net/pdf?id=FMjeC9Msws
  learning_rate: 5e-7
  lr_scheduler_type: constant
  warmup_steps: 100
  optim: adamw_8bit
  weight_decay: 0.01
  adam_epsilon: 1e-15
  gradient_accumulation_steps: 4
  bf16: true
  report_to: wandb
  eval_strategy: epoch
  per_device_eval_batch_size: 4
  save_strategy: best
  save_total_limit: 1
  metric_for_best_model: eval_loss
  # SFTConfig
  model_init_kwargs:
    dtype: bfloat16
    attn_implementation: flash_attention_2
  max_length: null
  