defaults:
  - evaluate
  - _self_

stage: online_rl
init_from: ???
thinking_budget: 1024

build_dataset:
  stage: ${stage}
  num_designs: ${num_designs}
  val_design_ratio: 0.2
  seed: 42
  dataset_size: 1000
  num_shots: 10

grpo_config:
  # TrainingArguments
  output_dir: ${output_dir}
  per_device_train_batch_size: 8
  num_train_epochs: 10
  # https://openreview.net/pdf?id=FMjeC9Msws
  learning_rate: 5e-7
  lr_scheduler_type: constant
  warmup_steps: 100
  optim: adamw_8bit
  weight_decay: 0.01
  adam_epsilon: 1e-15
  gradient_accumulation_steps: 2
  bf16: true
  report_to: wandb
  eval_strategy: epoch
  per_device_eval_batch_size: 16
  save_strategy: best
  save_total_limit: 1
  metric_for_best_model: eval_loss
  # GRPOConfig
  model_init_kwargs:
    dtype: bfloat16
    attn_implementation: flash_attention_2
  num_generations: 8
  num_generations_eval: 2
  max_completion_length: ${llm.sampling_params.max_tokens}
  generation_batch_size: 32
  temperature: ${llm.sampling_params.temperature}
  top_p: ${llm.sampling_params.top_p}
  top_k: ${llm.sampling_params.top_k}
  min_p: ${llm.sampling_params.min_p}
  use_vllm: true
  vllm_mode: colocate
  vllm_max_model_length: ${llm.sampling_params.max_tokens}
  vllm_enable_sleep_mode: true
  epsilon: 0.2
  epsilon_high: 5.0
  loss_type: cispo
  mask_truncated_completions: true
