defaults:
  - base
  - _self_

run_name: ${stage_to_run_name.offline_rl}
base_model: ${stage_to_model.${offline_rl.base_model}}

build_dataset:
  scale_reward: ${offline_rl.scale_reward}
  response_ratio: ${offline_rl.response_ratio}
  num_candidates: ${offline_rl.num_candidates}
  num_permutations: ${offline_rl.num_permutations}
  num_shots: ${offline_rl.num_shots}

training_arguments:
  # TrainingArguments
  per_device_train_batch_size: 2
  num_train_epochs: 10
  # https://arxiv.org/pdf/2510.13786
  learning_rate: 5e-7
  lr_scheduler_type: constant
  warmup_steps: 100
  weight_decay: 0.01
  adam_epsilon: 1e-15
  gradient_accumulation_steps: 4
  per_device_eval_batch_size: 2
  # SFTConfig
  model_init_kwargs:
    dtype: bfloat16
  max_length: null
