defaults:
  - override hydra/job_logging: disabled
  - override hydra/hydra_logging: disabled
  - _self_

hydra:
  run:
    dir: .
  output_subdir: null
  job:
    chdir: false

dataset:
  task_name: TFBind8-Exact-v0
  train_size: 1000
  val_size: 1000
  response_ratio: 0.2
  num_references: 10
  num_permutations: 2
  seed: 42

trainer_cfg:
  output_dir: output/${run_name}
  eval_strategy: steps
  num_train_epochs: 10
  eval_steps: 20
  report_to: wandb

run_name: offline_rl
model: Qwen/Qwen3-4B
