defaults:
  - base
  - _self_

run_name: "${hydra:runtime.choices.llm}/\
  ${task_name}/d${dataset_size}_s${num_shots}/\
  c${num_candidates}_p${num_permutations}/\
  train_online/d${online_dataset_size}"

online_dataset_size: 500

dataset:
  task_name: ${task_name}
  dataset_size: ${dataset_size}
  val_size: 0.2
  random_state: 42
  # online RL
  online_dataset_size: ${online_dataset_size}
  num_shots: ${num_shots}

trainer_args:
  output_dir: outputs/${run_name}
  eval_strategy: epoch
  # training
  per_device_train_batch_size: 4
  per_device_eval_batch_size: 4
  gradient_accumulation_steps: 1
  learning_rate: 1e-6
  num_train_epochs: 3
  lr_scheduler_type: linear
  # saving
  save_strategy: best
  save_total_limit: 1
  # evaluation
  seed: 42
  load_best_model_at_end: true
  metric_for_best_model: eval_loss
  greater_is_better: false
  # logging
  report_to: wandb
  # GRPOConfig
  num_generations: 4
  generation_kwargs: ${llm.vllm_generation_kwargs}
  use_vllm: true
  vllm_mode: colocate
  vllm_max_model_length: ${llm.hf_generation_kwargs.max_new_tokens}
  beta: 0.0
  epsilon: 0.2
  epsilon_high: 0.28
  loss_type: dapo
  mask_truncated_completions: true
