defaults:
  - llm: qwen3-4b
  - _self_

hydra:
  run:
    dir: ${output_dir}

task: tf8
stage: base
subset_size: 500

wandb_init:
  project: LLM4BBO-HF
  dir: outputs/${.name}
  name: "${hydra:runtime.choices.llm}/${task}/ss${subset_size}/\
    ${stage}/${now:%Y-%m-%d_%H-%M-%S}"
  job_type: ${stage}

evaluate:
  num_trials: 8
  num_proposals: 128
  num_shots: 10
  thinking_budget: 12288
